lexik_jwt_authentication:
    secret_key:   '%kernel.project_dir%/config/jwt/private.pem'
    public_key:   '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase:  'tu_frase_secreta'
    token_ttl:    3600 # Tiempo de vida del token en segundos (1 hora)
