security:
    password_hashers:
        App\Entity\Usuario:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Usuario
                property: username  # Cambiar 'email' por 'username' porque en tu entidad se usa 'username'

    firewalls:
        api:
            pattern: ^/api/
            stateless: true
            # Si estás usando JWT, probablemente tengas un bundle como lexik/jwt-authentication-bundle
            jwt: ~  

        main:
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_muro
            logout:
                path: app_logout
                target: /login

    access_control:
        - { path: ^/api, roles: ROLE_USER }  # Acceso a la API solo para usuarios autenticados con ROLE_USER
