security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Cliente
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # pattern: ^/api
            # stateless: false
            lazy: true
            provider: app_user_provider
            entry_point: jwt
            
            json_login:
                check_path: /api/login
                username_path: username
                password_path: password
                success_handler: App\Security\JwtSuccessHandler

            jwt: 

            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_finalizar_pedido


            logout:
                path: app_logout
                # where to redirect after logout
                target: app_login

    access_control:        
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_USER }
