controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

auth_login:
    path: /api/login
    # si tuvieramos un controlador de autenticacion propio
    #controller: App\Controller\AuthController::login 
    methods: [GET, POST]    
